language: cpp

os:
  - linux
  - osx
  
addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - yasm
      - nasm
      - cmake
      - libfftw3-dev
      - libmp3lame-dev
      - libpng-dev
    update: true
  homebrew:
    packages:
      - lame
      - automake
      - libtool
      - sdl
      - shtool
      - texi2html
      - theora
      - wget
      - nasm
      - cmake
      - fftw
      - libpng

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      
before_install:
  - unset CXX CXX_FOR_BUILD CC CC_FOR_BUILD

script: ./build-travis.sh
