language: cpp

os:
  - linux
  - osx
  
addons:
  apt:
    packages:
      - gcc-multilib
      - g++-multilib
      - yasm
      - nasm
      - cmake
      - libfftw3-dev
      - libmp3lame-dev
      - libpng-dev
    update: true
  homebrew:
    packages:
      - lame
      - cmake
      - fftw
      - libpng
      
before_install:
  - unset CXX CXX_FOR_BUILD CC CC_FOR_BUILD

script: ./build-travis.sh
